import React, { useState, useRef, useEffect } from 'react'
import poeOptionsJson from '../../data/poe_options.json'

// ── Types ─────────────────────────────────────────────────────────────────────

interface OptionChoice { value: number; name: string; display_name: string }
interface NamedValue   { value: number; name: string; display_name: string }
interface BossGroups   { Guardian?: string[]; Pinnacle?: string[]; Uber?: string[] }

type OptionType = 'choice' | 'toggle' | 'range' | 'option_set' | 'unknown'
type OptionValue = number | string | string[] | Record<string, number>

interface OptionDef {
  name: string
  display_name: string
  type: OptionType
  description?: string
  choices?: OptionChoice[]
  range_start?: number
  range_end?: number
  named_values?: NamedValue[]
  valid_keys?: string[]
  boss_groups?: BossGroups
  default?: number | string | string[]
}

interface Group       { name: string; options: OptionDef[] }
interface VersionInfo { world_version?: string; ap_version?: string; minimum_ap_version?: string }
interface OptionsData {
  game: string
  groups: Group[]
  presets: Record<string, Record<string, unknown>>
  version_info?: VersionInfo
}

// ── Helpers ───────────────────────────────────────────────────────────────────

const BUNDLED_DATA = poeOptionsJson as unknown as OptionsData
const DICT_UNKNOWNS = new Set(['start_inventory', 'start_inventory_from_pool', 'start_inventory_pool'])
const INVENTORY_OPTS  = new Set(['start_inventory'])
const COMBO_ITEM_OPTS = new Set(['local_items', 'non_local_items', 'start_hints'])
const CAT_ORDER: (keyof BossGroups)[] = ['Guardian', 'Pinnacle', 'Uber']

function defaultFor(opt: OptionDef): OptionValue {
  if (opt.type === 'option_set') return (opt.default as string[] | undefined) ?? []
  if (opt.type === 'toggle')     return (opt.default as number | undefined) ?? 0
  if (opt.type === 'range')      return (opt.default as number | undefined) ?? opt.range_start ?? 0
  if (opt.type === 'choice') {
    const d = opt.default
    return d === 'random' ? 'random' : (d as number | undefined) ?? (opt.choices?.[0]?.value ?? 0)
  }
  if (INVENTORY_OPTS.has(opt.name)) return {}
  return ''
}

function buildDefaults(data: OptionsData): Record<string, OptionValue> {
  const out: Record<string, OptionValue> = {}
  for (const g of data.groups)
    for (const o of g.options)
      out[o.name] = defaultFor(o)
  return out
}

function generateYaml(data: OptionsData, values: Record<string, OptionValue>, playerName: string): string {
  const vi = data.version_info ?? {}
  const apVer    = vi.minimum_ap_version ?? vi.ap_version ?? '0.6.7'
  const worldVer = vi.world_version ?? '1.0.0'
  const pad = '  '
  const lines: string[] = [
    `name: ${playerName || 'Player'}`,
    '',
    'description: Generated by Path of Exile AP Options',
    '',
    'game: Path of Exile',
    'requires:',
    `  version: ${apVer}`,
    '  game:',
    `    Path of Exile: ${worldVer}`,
    '',
    'Path of Exile:',
  ]

  const addDesc = (desc?: string) => {
    if (!desc) return
    desc.split('\n').forEach(l => lines.push(`${pad}  # ${l}`))
  }

  for (const grp of data.groups) {
    lines.push('')
    const label = `# ${grp.name} #`
    const bar   = '#'.repeat(label.length)
    lines.push(`${pad}${bar}`)
    lines.push(`${pad}${label}`)
    lines.push(`${pad}${bar}`)

    for (const opt of grp.options) {
      lines.push('')
      lines.push(`${pad}${opt.name}:`)
      const val = values[opt.name] ?? defaultFor(opt)

      if (opt.type === 'choice') {
        addDesc(opt.description)
        const cur      = val
        const isRandom = cur === 'random'
        ;(opt.choices ?? []).forEach(c => {
          const w = !isRandom && c.value === Number(cur) ? 50 : 0
          lines.push(`${pad}  ${c.name}: ${w}`)
        })
        if (isRandom) lines.push(`${pad}  random: 50`)

      } else if (opt.type === 'toggle') {
        addDesc(opt.description)
        const isOn = Number(val) === 1
        lines.push(`${pad}  'false': ${isOn ? 0 : 50}`)
        lines.push(`${pad}  'true': ${isOn ? 50 : 0}`)

      } else if (opt.type === 'range') {
        addDesc(opt.description)
        lines.push(`${pad}  #`)
        lines.push(`${pad}  # Minimum value is ${opt.range_start}`)
        lines.push(`${pad}  # Maximum value is ${opt.range_end}`)
        const cur = Number(val)
        if (opt.named_values?.length) {
          lines.push(`${pad}  random: 0`)
          lines.push(`${pad}  random-low: 0`)
          lines.push(`${pad}  random-high: 0`)
          lines.push(`${pad}  random-range-${opt.range_start}-${opt.range_end}: 0`)
          opt.named_values.forEach(nv => {
            lines.push(`${pad}  ${nv.name}: ${nv.value === cur ? 50 : 0} # equivalent to ${nv.value}`)
          })
        } else {
          lines.push(`${pad}  ${cur}: 50`)
          lines.push(`${pad}  random: 0`)
          lines.push(`${pad}  random-low: 0`)
          lines.push(`${pad}  random-high: 0`)
          lines.push(`${pad}  random-range-${opt.range_start}-${opt.range_end}: 0`)
        }

      } else if (opt.type === 'option_set') {
        addDesc(opt.description)
        const checked = val as string[]
        if (!checked.length) {
          lines.push(`${pad}  []`)
        } else {
          lines.push(`${pad}  [${checked.map(k => `'${k}'`).join(', ')}]`)
        }

      } else if (opt.type === 'unknown') {
        addDesc(opt.description)
        if (INVENTORY_OPTS.has(opt.name)) {
          const dict = val as Record<string, number>
          const entries = Object.entries(dict).filter(([, n]) => n > 0)
          if (entries.length) {
            entries.forEach(([item, n]) => lines.push(`${pad}  "${item}": ${n}`))
          } else {
            lines.push(`${pad}  {}`)
          }
        } else {
          lines.push(`${pad}  ${DICT_UNKNOWNS.has(opt.name) ? '{}' : '[]'}`)
        }
      }
    }
  }

  return lines.join('\n')
}

// ── Styles ────────────────────────────────────────────────────────────────────

const selectStyle: React.CSSProperties = {
  width: '100%',
  background: 'var(--bg)',
  border: '1px solid var(--rule-2)',
  color: 'var(--ink)',
  fontFamily: 'var(--sans)',
  fontSize: 12,
  padding: '4px 8px',
  borderRadius: 3,
  outline: 'none',
  cursor: 'pointer',
}

const checkBtnStyle: React.CSSProperties = {
  background: 'none',
  border: '1px solid var(--rule)',
  color: 'var(--ink-3)',
  fontFamily: 'var(--sans)',
  fontSize: 10.5,
  padding: '2px 8px',
  cursor: 'pointer',
  borderRadius: 2,
}

function checkItemStyle(active: boolean): React.CSSProperties {
  return {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    background: 'var(--bg)',
    border: `1px solid ${active ? 'var(--accent-2)' : 'var(--rule)'}`,
    borderRadius: 2,
    padding: '2px 6px',
    fontSize: 11,
    cursor: 'pointer',
    userSelect: 'none' as const,
    color: active ? 'var(--accent)' : 'var(--ink-2)',
    whiteSpace: 'nowrap' as const,
  }
}

// ── Sub-components ────────────────────────────────────────────────────────────

function Tip({ text }: { text: string }) {
  const [pos, setPos] = useState<{ x: number; y: number } | null>(null)
  const iconRef = useRef<HTMLSpanElement>(null)

  const show = () => {
    const r = iconRef.current?.getBoundingClientRect()
    if (r) setPos({ x: r.left, y: r.top - 8 })
  }

  return (
    <span style={{ display: 'inline-block' }}
      onMouseEnter={show} onMouseLeave={() => setPos(null)}>
      <span ref={iconRef} style={{
        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        width: 13, height: 13, borderRadius: '50%', border: '1px solid var(--ink-4)',
        color: 'var(--ink-4)', fontSize: 8.5, cursor: 'help', flexShrink: 0,
        fontFamily: 'var(--mono)',
      }}>?</span>
      {pos && (
        <div style={{
          position: 'fixed', left: pos.x, top: pos.y, transform: 'translateY(-100%)',
          zIndex: 9999,
          background: 'var(--panel-2)', border: '1px solid var(--rule-2)',
          color: 'var(--ink-2)', fontSize: 11, lineHeight: 1.5,
          padding: '6px 10px', borderRadius: 3, width: 260,
          whiteSpace: 'pre-wrap', pointerEvents: 'none',
          boxShadow: '0 4px 16px rgba(0,0,0,0.4)',
        }}>{text}</div>
      )}
    </span>
  )
}

function OptLabel({ opt }: { opt: OptionDef }) {
  return (
    <div style={{ fontSize: 11.5, marginBottom: 6, display: 'flex', alignItems: 'center', gap: 5, flexWrap: 'wrap' }}>
      <strong style={{ color: 'var(--accent)', fontWeight: 600 }}>{opt.display_name}</strong>
      {opt.description && <Tip text={opt.description} />}
    </div>
  )
}

function ChoiceOpt({ opt, value, onChange }: { opt: OptionDef; value: OptionValue; onChange: (v: OptionValue) => void }) {
  return (
    <select style={selectStyle} value={String(value)}
      onChange={e => onChange(e.target.value === 'random' ? 'random' : Number(e.target.value))}>
      {opt.default === 'random' && <option value="random">Random</option>}
      {(opt.choices ?? []).map(c => (
        <option key={c.value} value={c.value}>{c.display_name} ({c.value})</option>
      ))}
    </select>
  )
}

function ToggleOpt({ value, onChange }: { value: OptionValue; onChange: (v: OptionValue) => void }) {
  return (
    <select style={selectStyle} value={String(value)}
      onChange={e => onChange(Number(e.target.value))}>
      <option value="0">Off (0)</option>
      <option value="1">On (1)</option>
    </select>
  )
}

function RangeOpt({ opt, value, onChange }: { opt: OptionDef; value: OptionValue; onChange: (v: OptionValue) => void }) {
  const cur = Number(value)
  const valDisplay = (
    <span style={{ minWidth: '2.5rem', textAlign: 'right', color: 'var(--accent)', fontSize: 12, fontWeight: 'bold', fontFamily: 'var(--mono)' }}>{cur}</span>
  )
  const slider = (
    <input type="range" min={opt.range_start} max={opt.range_end} value={cur}
      style={{ flex: 1, accentColor: 'var(--accent)', cursor: 'pointer' }}
      onChange={e => onChange(Number(e.target.value))} />
  )

  if (opt.named_values?.length) {
    return (
      <div>
        <select style={{ ...selectStyle, marginBottom: 6 }} value={String(cur)}
          onChange={e => onChange(Number(e.target.value))}>
          {opt.named_values.map(nv => (
            <option key={nv.value} value={nv.value}>{nv.display_name} ({nv.value})</option>
          ))}
        </select>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>{slider}{valDisplay}</div>
      </div>
    )
  }

  return <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>{slider}{valDisplay}</div>
}

function OptionSetOpt({ opt, value, onChange }: { opt: OptionDef; value: OptionValue; onChange: (v: OptionValue) => void }) {
  const [search, setSearch] = useState('')
  const checked    = new Set(value as string[])
  const defaultSet = new Set((opt.default as string[] | undefined) ?? [])

  const allKeys = opt.boss_groups
    ? CAT_ORDER.flatMap(cat => opt.boss_groups![cat] ?? [])
    : (opt.valid_keys ?? [])

  const toggle  = (k: string) => { const s = new Set(checked); s.has(k) ? s.delete(k) : s.add(k); onChange([...s]) }
  const setAll  = (on: boolean) => onChange(on ? [...allKeys] : [])
  const reset   = () => onChange([...defaultSet])

  const actions = (
    <div style={{ display: 'flex', gap: 5, marginBottom: 8 }}>
      {(['All', 'None', 'Default'] as const).map(lbl => (
        <button key={lbl} type="button" style={checkBtnStyle}
          onClick={() => lbl === 'All' ? setAll(true) : lbl === 'None' ? setAll(false) : reset()}>
          {lbl}
        </button>
      ))}
    </div>
  )

  if (opt.boss_groups) {
    return (
      <div>
        {actions}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {CAT_ORDER.map(cat => {
            const keys = opt.boss_groups![cat] ?? []
            if (!keys.length) return null
            return (
              <div key={cat}>
                <div style={{ fontSize: 9.5, color: 'var(--accent-2)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 4, fontFamily: 'var(--mono)' }}>{cat}</div>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 4 }}>
                  {keys.map(k => (
                    <label key={k} style={checkItemStyle(checked.has(k))}>
                      <input type="checkbox" checked={checked.has(k)} onChange={() => toggle(k)}
                        style={{ accentColor: 'var(--accent)', margin: 0, cursor: 'pointer' }} />
                      {k.replace(/_/g, ' ')}
                    </label>
                  ))}
                </div>
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  const isLocation = ['start_location_hints', 'exclude_locations', 'priority_locations'].includes(opt.name)
  const keys       = opt.valid_keys ?? []
  const filtered   = search ? keys.filter(k => k.toLowerCase().includes(search.toLowerCase())) : keys

  if (isLocation) {
    const regularLocs = filtered.filter(k => !k.startsWith('Reach '))
    const areaLocs    = filtered.filter(k => k.startsWith('Reach '))
    const gridStyle: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 4 }
    const checkItem = (k: string) => (
      <label key={k} style={checkItemStyle(checked.has(k))}>
        <input type="checkbox" checked={checked.has(k)} onChange={() => toggle(k)}
          style={{ accentColor: 'var(--accent)', margin: 0, cursor: 'pointer' }} />
        {k.replace(/_/g, ' ')}
      </label>
    )
    return (
      <div>
        {actions}
        {keys.length > 20 && (
          <input type="text" className="input" placeholder="Search…" value={search}
            onChange={e => setSearch(e.target.value)}
            style={{ marginBottom: 8, display: 'block', fontSize: 11.5 }} />
        )}
        <div style={{ maxHeight: 200, overflowY: 'auto' }}>
          {regularLocs.length > 0 && <div style={gridStyle}>{regularLocs.map(checkItem)}</div>}
          {regularLocs.length > 0 && areaLocs.length > 0 && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, margin: '8px 0 6px' }}>
              <hr style={{ flex: 1, border: 'none', borderTop: '1px solid var(--rule)', margin: 0 }} />
              <span style={{ fontSize: 9.5, color: 'var(--ink-4)', fontFamily: 'var(--mono)', textTransform: 'uppercase', letterSpacing: '0.08em', whiteSpace: 'nowrap' }}>Areas</span>
              <hr style={{ flex: 1, border: 'none', borderTop: '1px solid var(--rule)', margin: 0 }} />
            </div>
          )}
          {areaLocs.length > 0 && <div style={gridStyle}>{areaLocs.map(checkItem)}</div>}
        </div>
      </div>
    )
  }

  return (
    <div>
      {actions}
      {keys.length > 20 && (
        <input type="text" className="input" placeholder="Search…" value={search}
          onChange={e => setSearch(e.target.value)}
          style={{ marginBottom: 8, display: 'block', fontSize: 11.5 }} />
      )}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, maxHeight: 200, overflowY: 'auto' }}>
        {filtered.map(k => (
          <label key={k} style={checkItemStyle(checked.has(k))}>
            <input type="checkbox" checked={checked.has(k)} onChange={() => toggle(k)}
              style={{ accentColor: 'var(--accent)', margin: 0, cursor: 'pointer' }} />
            {k.replace(/_/g, ' ')}
          </label>
        ))}
      </div>
    </div>
  )
}

function imgUrl(name: string) {
  return `ap-assets:///images/${name.toLowerCase().replace(/['\s]/g, '')}.png`
}

function StartInventoryOpt({ value, onChange, allItems }: {
  value: Record<string, number>; onChange: (v: Record<string, number>) => void; allItems: string[]
}) {
  const [input,     setInput]     = useState('')
  const [open,      setOpen]      = useState(false)
  const [activeIdx, setActiveIdx] = useState(-1)
  const wrapRef = useRef<HTMLDivElement>(null)
  const listRef = useRef<HTMLUListElement>(null)

  const filtered = input.trim()
    ? allItems.filter(n => !(n in value) && n.toLowerCase().includes(input.toLowerCase()))
    : allItems.filter(n => !(n in value))

  useEffect(() => { setActiveIdx(-1) }, [input])

  useEffect(() => {
    if (!open) return
    function onDown(e: MouseEvent) {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  }, [open])

  function select(name: string) {
    onChange({ ...value, [name]: 1 })
    setInput('')
    setOpen(false)
  }

  function onKey(e: React.KeyboardEvent) {
    if (!open && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) { setOpen(true); return }
    if (!open) return
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      const next = Math.min(activeIdx + 1, filtered.length - 1)
      setActiveIdx(next)
      listRef.current?.children[next]?.scrollIntoView({ block: 'nearest' })
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      const prev = Math.max(activeIdx - 1, 0)
      setActiveIdx(prev)
      listRef.current?.children[prev]?.scrollIntoView({ block: 'nearest' })
    } else if (e.key === 'Enter') {
      if (activeIdx >= 0 && filtered[activeIdx]) select(filtered[activeIdx])
    } else if (e.key === 'Escape') {
      setOpen(false)
    }
  }

  const setCount = (item: string, n: number) => {
    const next = { ...value }
    if (n <= 0) delete next[item]; else next[item] = n
    onChange(next)
  }

  const entries = Object.entries(value).filter(([, n]) => n > 0)

  return (
    <div>
      {entries.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 3, marginBottom: 8 }}>
          {entries.map(([item, n]) => (
            <div key={item} style={{ display: 'flex', alignItems: 'center', gap: 8,
              background: 'var(--bg)', border: '1px solid var(--accent-2)',
              borderRadius: 3, padding: '4px 8px' }}>
              <img src={imgUrl(item)} alt="" style={{ width: 20, height: 20, objectFit: 'contain', flexShrink: 0 }}
                onError={e => { (e.target as HTMLImageElement).style.display = 'none' }} />
              <span style={{ flex: 1, fontSize: 12, color: 'var(--accent)', fontFamily: 'var(--mono)' }}>{item}</span>
              <input type="number" min={1} max={99} value={n}
                onChange={e => setCount(item, Math.max(1, Number(e.target.value)))}
                style={{ width: 50, background: 'var(--bg-2)', border: '1px solid var(--rule-2)',
                  color: 'var(--ink)', fontFamily: 'var(--mono)', fontSize: 12,
                  padding: '2px 4px', borderRadius: 2, textAlign: 'center' }} />
              <button type="button" onClick={() => setCount(item, 0)}
                style={{ background: 'none', border: 'none', color: 'var(--ink-4)',
                  cursor: 'pointer', fontSize: 13, padding: '0 2px', lineHeight: 1 }}>✕</button>
            </div>
          ))}
        </div>
      )}
      <div ref={wrapRef} style={{ position: 'relative' }}>
        <input className="input mono" style={{ width: '100%', fontSize: 12, boxSizing: 'border-box' }}
          placeholder="Add item…"
          value={input}
          onChange={e => { setInput(e.target.value); setOpen(true) }}
          onFocus={() => setOpen(true)}
          onKeyDown={onKey} />
        {open && filtered.length > 0 && (
          <ul ref={listRef} style={{
            position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 200,
            margin: 0, padding: '4px 0', listStyle: 'none',
            background: 'var(--bg-3)', border: '1px solid var(--rule-2)',
            borderRadius: 5, maxHeight: 220, overflowY: 'auto',
            boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
          }}>
            {filtered.map((n, i) => (
              <li key={n}
                onMouseDown={() => select(n)}
                onMouseEnter={() => setActiveIdx(i)}
                style={{
                  display: 'flex', alignItems: 'center', gap: 8,
                  padding: '5px 10px', cursor: 'default', fontSize: 12,
                  background: i === activeIdx ? 'var(--accent-soft)' : 'transparent',
                  color: i === activeIdx ? 'var(--ink)' : 'var(--ink-2)',
                }}>
                <img src={imgUrl(n)} alt="" style={{ width: 22, height: 22, objectFit: 'contain', flexShrink: 0 }}
                  onError={e => { (e.target as HTMLImageElement).style.display = 'none' }} />
                <span className="mono">{n}</span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  )
}

function ComboSetOpt({ value, onChange, allItems }: {
  value: string[]; onChange: (v: string[]) => void; allItems: string[]
}) {
  const [input,     setInput]     = useState('')
  const [open,      setOpen]      = useState(false)
  const [activeIdx, setActiveIdx] = useState(-1)
  const wrapRef = useRef<HTMLDivElement>(null)
  const listRef = useRef<HTMLUListElement>(null)
  const selected = new Set(value)

  const filtered = input.trim()
    ? allItems.filter(n => !selected.has(n) && n.toLowerCase().includes(input.toLowerCase()))
    : allItems.filter(n => !selected.has(n))

  useEffect(() => { setActiveIdx(-1) }, [input])

  useEffect(() => {
    if (!open) return
    function onDown(e: MouseEvent) {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  }, [open])

  function select(name: string) {
    onChange([...value, name])
    setInput('')
    setOpen(false)
  }

  function remove(name: string) {
    onChange(value.filter(v => v !== name))
  }

  function onKey(e: React.KeyboardEvent) {
    if (!open && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) { setOpen(true); return }
    if (!open) return
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      const next = Math.min(activeIdx + 1, filtered.length - 1)
      setActiveIdx(next)
      listRef.current?.children[next]?.scrollIntoView({ block: 'nearest' })
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      const prev = Math.max(activeIdx - 1, 0)
      setActiveIdx(prev)
      listRef.current?.children[prev]?.scrollIntoView({ block: 'nearest' })
    } else if (e.key === 'Enter') {
      if (activeIdx >= 0 && filtered[activeIdx]) select(filtered[activeIdx])
    } else if (e.key === 'Escape') {
      setOpen(false)
    }
  }

  return (
    <div>
      {value.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 3, marginBottom: 8 }}>
          {value.map(item => (
            <div key={item} style={{ display: 'flex', alignItems: 'center', gap: 8,
              background: 'var(--bg)', border: '1px solid var(--accent-2)',
              borderRadius: 3, padding: '4px 8px' }}>
              <img src={imgUrl(item)} alt="" style={{ width: 20, height: 20, objectFit: 'contain', flexShrink: 0 }}
                onError={e => { (e.target as HTMLImageElement).style.display = 'none' }} />
              <span style={{ flex: 1, fontSize: 12, color: 'var(--accent)', fontFamily: 'var(--mono)' }}>{item}</span>
              <button type="button" onClick={() => remove(item)}
                style={{ background: 'none', border: 'none', color: 'var(--ink-4)',
                  cursor: 'pointer', fontSize: 13, padding: '0 2px', lineHeight: 1 }}>✕</button>
            </div>
          ))}
        </div>
      )}
      <div ref={wrapRef} style={{ position: 'relative' }}>
        <input className="input mono" style={{ width: '100%', fontSize: 12, boxSizing: 'border-box' }}
          placeholder="Add item…"
          value={input}
          onChange={e => { setInput(e.target.value); setOpen(true) }}
          onFocus={() => setOpen(true)}
          onKeyDown={onKey} />
        {open && filtered.length > 0 && (
          <ul ref={listRef} style={{
            position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 200,
            margin: 0, padding: '4px 0', listStyle: 'none',
            background: 'var(--bg-3)', border: '1px solid var(--rule-2)',
            borderRadius: 5, maxHeight: 220, overflowY: 'auto',
            boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
          }}>
            {filtered.map((n, i) => (
              <li key={n}
                onMouseDown={() => select(n)}
                onMouseEnter={() => setActiveIdx(i)}
                style={{
                  display: 'flex', alignItems: 'center', gap: 8,
                  padding: '5px 10px', cursor: 'default', fontSize: 12,
                  background: i === activeIdx ? 'var(--accent-soft)' : 'transparent',
                  color: i === activeIdx ? 'var(--ink)' : 'var(--ink-2)',
                }}>
                <img src={imgUrl(n)} alt="" style={{ width: 22, height: 22, objectFit: 'contain', flexShrink: 0 }}
                  onError={e => { (e.target as HTMLImageElement).style.display = 'none' }} />
                <span className="mono">{n}</span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  )
}

function OptionRow({ opt, value, onChange, isDefeatBosses, allItems }: {
  opt: OptionDef; value: OptionValue; onChange: (v: OptionValue) => void; isDefeatBosses: boolean; allItems: string[]
}) {
  if (opt.type === 'unknown' && !INVENTORY_OPTS.has(opt.name)) return null
  if (['number_of_bosses', 'bosses_available'].includes(opt.name) && !isDefeatBosses) return null

  const isFullWidth = opt.type === 'option_set' || INVENTORY_OPTS.has(opt.name) || COMBO_ITEM_OPTS.has(opt.name)

  let control: React.ReactNode = null
  if      (opt.type === 'choice')             control = <ChoiceOpt opt={opt} value={value} onChange={onChange} />
  else if (opt.type === 'toggle')             control = <ToggleOpt value={value} onChange={onChange} />
  else if (opt.type === 'range')              control = <RangeOpt opt={opt} value={value} onChange={onChange} />
  else if (COMBO_ITEM_OPTS.has(opt.name))     control = <ComboSetOpt value={value as string[]} onChange={onChange as (v: string[]) => void} allItems={allItems} />
  else if (opt.type === 'option_set')         control = <OptionSetOpt opt={opt} value={value} onChange={onChange} />
  else if (INVENTORY_OPTS.has(opt.name))      control = <StartInventoryOpt value={value as Record<string, number>} onChange={onChange as (v: Record<string, number>) => void} allItems={allItems} />

  return (
    <div style={{
      padding: '10px 14px',
      borderBottom: '1px solid var(--rule)',
      borderRight: isFullWidth ? 'none' : '1px solid var(--rule)',
      gridColumn: isFullWidth ? '1 / -1' : undefined,
    }}>
      <OptLabel opt={opt} />
      {control}
    </div>
  )
}

// ── Main screen ───────────────────────────────────────────────────────────────

export function YamlGeneratorScreen() {
  const data                         = BUNDLED_DATA
  const [values,     setValues]     = useState<Record<string, OptionValue>>(() => buildDefaults(data))
  const [playerName, setPlayerName] = useState('')
  const [preset,     setPreset]     = useState('')

  const setVal = (name: string) => (v: OptionValue) =>
    setValues(prev => ({ ...prev, [name]: v }))

  const applyPreset = (name: string) => {
    setPreset(name)
    const base      = buildDefaults(data)
    const overrides = name ? (data.presets[name] ?? {}) : {}
    const byName    = Object.fromEntries(data.groups.flatMap(g => g.options).map(o => [o.name, o]))
    const merged    = { ...base }
    for (const [k, v] of Object.entries(overrides))
      if (byName[k]) merged[k] = Array.isArray(v) ? (v as string[]) : (v as OptionValue)
    setValues(merged)
  }

  const download = () => {
    if (!data) return
    const name = playerName.trim() || 'Player'
    const yaml = generateYaml(data, values, name)
    const blob = new Blob([yaml], { type: 'text/yaml' })
    const url  = URL.createObjectURL(blob)
    Object.assign(document.createElement('a'), { href: url, download: `${name}.yaml` }).click()
    URL.revokeObjectURL(url)
  }

  const goalOpt          = data?.groups.flatMap(g => g.options).find(o => o.name === 'goal')
  const defeatBossesVal  = goalOpt?.choices?.find(c => c.name === 'defeat_bosses')?.value
  const isDefeatBosses   = values['goal'] === defeatBossesVal
  const allItems         = data?.groups.flatMap(g => g.options).find(o => o.name === 'local_items')?.valid_keys ?? []

  const existingChar = isDefeatBosses
    && Number(values['add_leveling_up_to_location_pool']) === 0
    && Number(values['add_area_locations_to_location_pool']) === 0

  const toggleExistingChar = () => {
    if (existingChar) {
      // uncheck — revert goal back to default
      const goalDef = defaultFor(goalOpt!)
      setValues(prev => ({ ...prev, goal: goalDef }))
    } else {
      setValues(prev => ({
        ...prev,
        goal: defeatBossesVal!,
        add_leveling_up_to_location_pool: 0,
        add_area_locations_to_location_pool: 0,
      }))
    }
  }

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

      {/* Header */}
      <div className="page-header" style={{ flexShrink: 0 }}>
        <h1>Yaml Generator</h1>
        <div className="sub">Generate a <code>.yaml</code> config file for Archipelago multiworlds</div>
      </div>

      <>
          {/* Meta row */}
          <div style={{
            padding: '12px 20px',
            borderBottom: '1px solid var(--rule)',
            display: 'flex', gap: 20, flexWrap: 'wrap', alignItems: 'flex-end',
            flexShrink: 0, background: 'var(--bg-2)',
          }}>
            <div>
              <label className="label" htmlFor="yaml-player-name">Player Name</label>
              <input id="yaml-player-name" className="input" type="text"
                placeholder="Player" maxLength={16} value={playerName}
                onChange={e => setPlayerName(e.target.value)}
                style={{ width: 200 }} />
            </div>
            <div>
              <label className="label" htmlFor="yaml-preset">Options Preset</label>
              <select id="yaml-preset" className="input select" value={preset}
                onChange={e => applyPreset(e.target.value)}
                style={{ width: 240 }}>
                <option value="">Default</option>
                {Object.keys(data.presets).map(p => (
                  <option key={p} value={p}>{p}</option>
                ))}
              </select>
            </div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 7, cursor: 'pointer', paddingBottom: 4, userSelect: 'none', fontSize: 12.5, color: existingChar ? 'var(--accent)' : 'var(--ink-2)' }}>
              <input type="checkbox" checked={existingChar} onChange={toggleExistingChar}
                style={{ accentColor: 'var(--accent)', cursor: 'pointer', width: 14, height: 14 }} />
              Existing Character
            </label>
          </div>

          {/* Scrollable groups */}
          <div style={{ flex: 1, overflowY: 'auto', padding: '12px 20px' }}>
            {data.groups.map(grp => {
              const visibleOpts = grp.options.filter(o => {
                if (o.type === 'unknown' && !INVENTORY_OPTS.has(o.name)) return false
                if (['number_of_bosses', 'bosses_available'].includes(o.name) && !isDefeatBosses) return false
                return true
              })
              if (!visibleOpts.length) return null
              return (
                <details key={grp.name} open={!['Item & Location Options', 'Other'].includes(grp.name)}
                  style={{ background: 'var(--panel)', border: '1px solid var(--rule)', borderRadius: 4, marginBottom: 8 }}>
                  <summary style={{
                    fontFamily: 'var(--display)', fontSize: 13, color: 'var(--accent)',
                    padding: '10px 14px', cursor: 'pointer', userSelect: 'none',
                    borderBottom: '1px solid var(--rule)', letterSpacing: '0.05em',
                    listStyle: 'none', display: 'flex', alignItems: 'center', gap: 8,
                  }}>
                    <span className="details-arrow" style={{ fontFamily: 'var(--mono)', color: 'var(--accent-2)', fontSize: 16, lineHeight: 1 }}>▾</span>
                    {grp.name}
                  </summary>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr' }}>
                    {grp.options.map(opt => (
                      <OptionRow key={opt.name} opt={opt}
                        value={values[opt.name] ?? defaultFor(opt)}
                        onChange={setVal(opt.name)}
                        isDefeatBosses={isDefeatBosses}
                        allItems={allItems} />
                    ))}
                  </div>
                </details>
              )
            })}
          </div>

          {/* Download bar */}
          <div style={{
            flexShrink: 0,
            background: 'var(--bg-2)',
            borderTop: '1px solid var(--rule)',
            padding: '10px 20px',
            display: 'flex', alignItems: 'center', gap: 16,
          }}>
            <span style={{ fontSize: 11.5, color: 'var(--ink-3)', flex: 1 }}>
              Options are not saved — download to keep them.
            </span>
            <button onClick={download} className="btn primary" style={{ fontSize: 13, padding: '8px 24px' }}>
              ⬇ Download .yaml
            </button>
          </div>
      </>
    </div>
  )
}
